---
- name: Install Zsh
  apt:
    name: zsh
    state: present
  tags: zsh

- name: Change default shell to zsh for the current user
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Install git
  apt:
    name: git
    state: present
  tags: zsh

- name: Install Oh My Zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags: zsh

- name: Copy .zshrc from Oh My Zsh template
  copy:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    remote_src: yes
  tags: zsh

- name: Set ZSH variable in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^export ZSH='
    line: 'export ZSH="{{ ansible_env.HOME }}/.oh-my-zsh"'
    state: present
  tags: zsh

- name: Clone fzf-zsh-plugin
  git:
    repo: 'https://github.com/unixorn/fzf-zsh-plugin.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
  tags: zsh

- name: Clone zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags: zsh

- name: Ensure plugins are set in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git fzf-zsh-plugin zsh-syntax-highlighting)'
    state: present
  tags: zsh

- name: Source .zshrc
  shell: source "{{ ansible_env.HOME }}/.zshrc"
  args:
    executable: /bin/zsh
  tags: zsh

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Clone Powerlevel10k repository
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '/home{{ ansible_user }}/powerlevel10k'

- name: Ensure ~/.zshrc exists
  file:
    path: "/home/{{ ansible_user }}/.zshrc"
    state: touch

- name: Add Powerlevel10k to Zsh configuration
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: '^source /home/{{ ansible_user }}/powerlevel10k/powerlevel10k.zsh-theme'
    line: 'source /home/{{ ansible_user }}/powerlevel10k/powerlevel10k.zsh-theme'
    state: present

- name: Copy Powerlevel10k configuration
  copy:
    src: "/home/{{ ansible_user }}/dotfiles/.p10k.zsh"
    dest: "/home/{{ ansible_user }}/.p10k.zsh"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Set EDITOR to nvim in Zsh configuration
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: '^export EDITOR='
    line: 'export EDITOR=nvim'
    state: present

- name: Add direnv hook to Zsh configuration
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: '^eval "$(direnv hook zsh)"'
    line: 'eval "$(direnv hook zsh)"'
    state: present

- name: Add aliases to .zshrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: "{{ item }}"
    create: yes
    state: present
  loop:
    - "alias dir='dir --color=auto'"
    - "alias egrep='egrep --color=auto'"
    - "alias fgrep='fgrep --color=auto'"
    - "alias grep='grep --color=auto'"
    - "alias la='ls -A'"
    - "alias ll='ls -alF'"
    - "alias ls='exa -l --icons -a'"
    - "alias lt='exa --tree --level=2 --long --icons'"
    - "alias mc='source /usr/lib/mc/mc-wrapper.sh'"
    - "alias nvimdiff='git difftool --tool=nvimdiff'"
    - "alias vdir='vdir --color=auto'"
    - "alias which-command='whence'"
    - "alias z='zshz 2>&1'"
    - "alias cat=batcat"

- name: Ensure zsh-z plugin is installed
  ansible.builtin.git:
    repo: https://github.com/agkozak/zsh-z
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-z"
    version: master
  become: yes

- name: Ensure zsh-autosuggestions plugin is installed
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
  become: yes

- name: Ensure git plugin is installed
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/git"
    version: master
  become: yes

- name: Add zsh-z plugin source to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: 'source /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-z/zsh-z.plugin.zsh'
    insertafter: EOF
    state: present

- name: Add zsh-autosuggestions plugin source to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: 'source /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh'
    insertafter: EOF
    state: present

- name: Add git plugin source to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: 'source /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/git/git.plugin.zsh'
    insertafter: EOF
    state: present

- name: Source .zshrc
  shell: source ""/home/{{ ansible_user }}/.zshrc"
  args:
    executable: /bin/zsh
  tags: zsh
