---
- name: Install Zsh
  apt:
    name: zsh
    state: present
  tags: zsh

- name: Change default shell to zsh for the current user
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Install git
  apt:
    name: git
    state: present
  tags: zsh

- name: Install Oh My Zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags: zsh

- name: Copy .zshrc from Oh My Zsh template
  copy:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    remote_src: yes
  tags: zsh

- name: Set ZSH variable in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^export ZSH='
    line: 'export ZSH="{{ ansible_env.HOME }}/.oh-my-zsh"'
    state: present
  tags: zsh

- name: Clone fzf-zsh-plugin
  git:
    repo: 'https://github.com/unixorn/fzf-zsh-plugin.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
  tags: zsh

- name: Clone zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags: zsh

- name: Ensure plugins are set in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git fzf-zsh-plugin zsh-syntax-highlighting)'
    state: present
  tags: zsh

- name: Source .zshrc
  shell: source "{{ ansible_env.HOME }}/.zshrc"
  args:
    executable: /bin/zsh
  tags: zsh

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Clone Powerlevel10k repository
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '/home{{ ansible_user }}/powerlevel10k'

- name: Ensure ~/.zshrc exists
  file:
    path: "/home/{{ ansible_user }}/.zshrc"
    state: touch

- name: Add Powerlevel10k to Zsh configuration
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: '^source /home/{{ ansible_user }}/powerlevel10k/powerlevel10k.zsh-theme'
    line: 'source /home/{{ ansible_user }}/powerlevel10k/powerlevel10k.zsh-theme'
    state: present

- name: Copy Powerlevel10k configuration
  copy:
    src: "/home/{{ ansible_user }}/dotfiles/.p10k.zsh"
    dest: "/home/{{ ansible_user }}/.p10k.zsh"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Set EDITOR to nvim in Zsh configuration
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: '^export EDITOR='
    line: 'export EDITOR=nvim'
    state: present
