---
- name: Add Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  tags: neovim

- name: Install Neovim
  apt:
    name: neovim
    state: present
  tags: neovim

- name: Ensure Python support for Neovim
  apt:
    name: "{{ item }}"
  with_items:
    - python3-neovim
    - python3-pip
  tags: neovim

- name: Install pynvim
  pip:
    name: pynvim
    executable: pip3
  tags: neovim

- name: Install Vimplug for Neovim
  become: yes
  tags: neovim
  ansible.builtin.shell: |
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Copy init.vim to Neovim configuration directory
  # become: yes
  tags: neovim
  ansible.builtin.copy:
    src: "/home/{{ ansible_user }}/dotfiles/init.vim"
    dest: "/home/{{ ansible_user }}/.config/nvim/init.vim"
    mode: '0644'

- name: Install plugins using Vimplug
  become: yes
  tags: neovim
  ansible.builtin.shell: |
    nvim --headless +PlugInstall +qa
