---
- name: Add Neovim PPA repository
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    state: present

- name: Update APT package cache
  become: true
  apt:
    update_cache: yes

- name: Install Neovim
  become: true
  apt:
    name: neovim
    state: present

- name: Ensure Python support for Neovim
  apt:
    name: "{{ item }}"
  with_items:
    - python3-neovim
    - python3-pip

- name: Install pynvim
  ansible.builtin.command:
      cmd: pip3 install pynvim --break-system-packages
      
- name: Install venv
  ansible.builtin.command:
      cmd: pip3 install --upgrade virtualenv --break-system-packages

- name: Install debugpy
  ansible.builtin.command:
      cmd: pip3 install debugpy --break-system-packages     

- name: Ensure directory for Neovim exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.local/share/nvim/site/autoload/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Install Vimplug for Neovim
  tags: neovim
  ansible.builtin.shell: |
    curl -fLo /home/{{ ansible_user }}/.local/share/nvim/site/autoload/plug.vim \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Ensure directory for Neovim exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/nvim/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy init.vim to Neovim configuration directory
  tags: neovim
  ansible.builtin.copy:
    src: "/home/{{ ansible_user }}/dotfiles/init.vim"
    dest: "/home/{{ ansible_user }}/.config/nvim/init.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Install plugins using Vimplug
  tags: neovim
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    nvim --headless +PlugInstall +qa

- name: Install packages using apt
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
#    - terraform-ls
    - golang
    - gopls
    - delve
    - tidy
    - nodejs
    - npm

- name: Install npm packages globally
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - bash-language-server
    - pyright
    - yaml-language-server
    - typescript
    - typescript-language-server

