---
- name: Install Tmux
  become: yes
  apt:
    name: tmux
    state: present

- name: Ensure directory for TPM exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Clone tpm (Tmux Plugin Manager) repository
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"

- name: Copy tmux configuration
  copy:
    src: "/home/{{ ansible_user }}/dotfiles/.tmux.conf"
    dest: "/home/{{ ansible_user }}/.tmux.conf"
