---
- name: Install Tmux
  apt:
    name: tmux
    state: present
  tags: tmux

- name: Install git (required for tpm)
  become: yes
  ansible.builtin.apt:
    name: git
    state: present

- name: Clone tpm (Tmux Plugin Manager) repository
  become: yes
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"

- name: Copy tmux configuration
  copy:
    src: "/home/{{ ansible_user }}/dotfiles/.tmux.conf"
    dest: "/home/{{ ansible_user }}/.tmux.conf"
  tags: tmux

- name: Install tmux plugins using tpm
  ansible.builtin.shell: |
    "/home/{{ ansible_user }}/.tmux/plugins/tpm/bin/install_plugins"
  args:
    executable: /bin/bash
    creates: "/home/{{ ansible_user }}/.tmux/plugins/tpm/installed"
  environment:
    TMUX_PLUGIN_MANAGER_PATH: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
    TMUX_PLUGIN_MANAGER_PATH_INSTALL: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
