---
- name: Setup development environment
  hosts: all
  become: true

  roles:
    - role: zsh
      tags: zsh
    - role: neovim
      tags: neovim
    - role: tmux
      tags: tmux
    - role: apt
      tags: apt
