---
- name: Setup development environment
  hosts: all
#  become: true
   
  vars:
    FZF_PATH: "/home/{{ ansible_user }}/.fzf"

  roles:
    - role: zsh
      tags: zsh
    - role: neovim
      tags: neovim
    - role: tmux
      tags: tmux
    - role: apt
      tags: apt
